In [5]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/02_Filtering_%26_Sorting/Euro12/Euro_2012_stats_TEAM.csv')

In [4]:
df.head()

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
0,Croatia,4,13,12,51.9%,16.0%,32,0,0,0,...,13,81.3%,41,62,2,9,0,9,9,16
1,Czech Republic,4,13,18,41.9%,12.9%,39,0,0,0,...,9,60.1%,53,73,8,7,0,11,11,19
2,Denmark,4,10,10,50.0%,20.0%,27,1,0,0,...,10,66.7%,25,38,8,4,0,7,7,15
3,England,5,11,18,50.0%,17.2%,40,0,0,0,...,22,88.1%,43,45,6,5,0,11,11,16
4,France,3,22,24,37.9%,6.5%,65,1,0,0,...,6,54.6%,36,51,5,6,0,11,11,19

In [10]:
df[['Goals', 'Team']]

    Goals                 Team
0       4              Croatia
1       4       Czech Republic
2       4              Denmark
3       5              England
4       3               France
5      10              Germany
6       5               Greece
7       6                Italy
8       2          Netherlands
9       2               Poland
10      6             Portugal
11      1  Republic of Ireland
12      5               Russia
13     12                Spain
14      5               Sweden
15      2              Ukraine

In [12]:
df.loc[:, ['Team', 'Yellow Cards', 'Red Cards']]

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [31]:
df.loc[:, 'Penalty goals':'Team':-1]

,Penalty goals,Hit Woodwork,Total shots (inc. Blocked),% Goals-to-shots,Shooting Accuracy,Shots off target,Shots on target,Goals,Team
0,0,0,32,16.0%,51.9%,12,13,4,Croatia
1,0,0,39,12.9%,41.9%,18,13,4,Czech Republic
2,0,1,27,20.0%,50.0%,10,10,4,Denmark
3,0,0,40,17.2%,50.0%,18,11,5,England
4,0,1,65,6.5%,37.9%,24,22,3,France
5,1,2,80,15.6%,47.8%,32,32,10,Germany
6,1,1,32,19.2%,30.7%,18,8,5,Greece
7,0,2,110,7.5%,43.0%,45,34,6,Italy
8,0,2,60,4.1%,25.0%,36,12,2,Netherlands
9,0,0,48,5.2%,39.4%,23,15,2,Poland
10,0,6,82,9.3%,34.3%,42,22,6,Portugal
11,0,0,28,5.2%,36.8%,12,7,1,Republic of Ireland
12,0,2,59,12.5%,22.5%,31,9,5,Russia
13,1,0,100,16.0%,55.9%,33,42,12,Spain
14,0,3,39,13.8%,47.2%,19,17,5,Sweden
15,0,0,38,6.0%,21.2%,26,7,2,Ukraine

In [23]:
df.iloc[2:5, 1:30:2]

,Goals,Shots off target,% Goals-to-shots,Hit Woodwork,Penalties not scored,Passes,Passing Accuracy,Crosses,Corners Taken,Clearances,Clearances off line,Blocks,Saves made,Fouls Won,Offsides
2,4,10,20.0%,1,0,1298,83.3%,43,16,61,0.0,10,10,25,8
3,5,18,17.2%,0,0,1488,80.6%,58,16,106,1.0,29,22,43,6
4,3,24,6.5%,1,0,2066,87.2%,55,28,76,0.0,7,6,36,5

In [22]:
df.at[1, 'Team']

'Czech Republic'

In [25]:
df.iloc[2:5, 30:1:-1]

,Yellow Cards,Offsides,Fouls Conceded,Fouls Won,Saves-to-shots ratio,Saves made,Goals conceded,Blocks,Clean Sheets,Clearances off line,...,Passes,Headed goals,Penalties not scored,Penalty goals,Hit Woodwork,Total shots (inc. Blocked),% Goals-to-shots,Shooting Accuracy,Shots off target,Shots on target
2,4,8,38,25,66.7%,10,5,10,1,0.0,...,1298,3,0,0,1,27,20.0%,50.0%,10,10
3,5,6,45,43,88.1%,22,3,29,2,1.0,...,1488,3,0,0,0,40,17.2%,50.0%,18,11
4,6,5,51,36,54.6%,6,5,7,1,0.0,...,2066,0,0,0,1,65,6.5%,37.9%,24,22

In [27]:
a = np.random.rand(100)

In [42]:
df['Yellow Cards'].mean()

7.4375

In [45]:
df[df['Goals'] > 6]

,Team,Goals,Shots on target,Shots off target,Shooting Accuracy,% Goals-to-shots,Total shots (inc. Blocked),Hit Woodwork,Penalty goals,Penalties not scored,...,Saves made,Saves-to-shots ratio,Fouls Won,Fouls Conceded,Offsides,Yellow Cards,Red Cards,Subs on,Subs off,Players Used
5,Germany,10,32,32,47.8%,15.6%,80,2,1,0,...,10,62.6%,63,49,12,4,0,15,15,17
13,Spain,12,42,33,55.9%,16.0%,100,0,1,0,...,15,93.8%,102,83,19,11,0,17,17,18

In [51]:
df.loc[df['Team'].isin(['Russia', 'Italy', 'England']), ["Team","Shooting Accuracy"]]

       Team Shooting Accuracy
3   England             50.0%
7     Italy             43.0%
12   Russia             22.5%